# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- Playerbot

pool:
  vmImage: ubuntu-latest

steps:
- script: mkdir build
- task: CmdLine@2
  inputs:
    script: 'sudo apt-get update && sudo apt-get install git cmake make gcc g++ clang libmysqlclient-dev libssl-dev libbz2-dev libreadline-dev libncurses-dev mysql-server libboost-all-dev'
    workingDirectory: './'

