name: Docker Image CI

on:
  push:
    branches: [ "Playerbot" ]
  pull_request:
    branches: [ "Playerbot" ]

env:
  master_sha: '5276676'
  playerbots_sha: '8816758'
  ah_bot_sha: '8b06eb4'
  solo_lfg_sha: '97bf902'
  arena_sha: 'd8fc2b6'
  eluna_sha: 'e00386f'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: git checkout $master_sha
      if: ${{ env.master_sha != '' }}
    - name: pwd && ls -l 
      run: pwd && ls -l 
    #gitag
    - name: make gitag
      run: echo GITAG=$(git log --pretty=format:"%h" -1) >> $GITHUB_ENV
      working-directory: ./
    #mod-playerbots
    - name: get mod-playerbots
      uses: actions/checkout@v4
      with:
        repository: liyunfan1223/mod-playerbots
        fetch-depth: 0
        path: modules/mod-playerbots
    - run: git checkout $playerbots_sha
      if: ${{ env.playerbots_sha != '' }}
      working-directory: modules/mod-playerbots
    - name: make gitag_mod_playerbots
      run: echo GITAG_MOD_PLAYERBOTS=bot$(git log --pretty=format:"%h" -1) >> $GITHUB_ENV
      working-directory: modules/mod-playerbots
    #mod-ah-bot
    - name: get mod-ah-bot
      uses: actions/checkout@v4
      with:
        repository: azerothcore/mod-ah-bot
        fetch-depth: 0
        path: modules/mod-ah-bot
    - run: git checkout $ah_bot_sha
      if: ${{ env.ah_bot_sha != '' }}
      working-directory: modules/mod-ah-bot
    - name: make gitag_mod_ah_bot
      run: echo GITAG_MOD_AH_BOT=ah$(git log --pretty=format:"%h" -1) >> $GITHUB_ENV
      working-directory: modules/mod-ah-bot
    #mod-solo-lfg
    - name: get mod-solo-lfg
      uses: actions/checkout@v4
      with:
        repository: azerothcore/mod-solo-lfg
        fetch-depth: 0
        path: modules/mod-solo-lfg
    - run: git checkout $solo_lfg_sha
      if: ${{ env.solo_lfg_sha != '' }}
      working-directory: modules/mod-solo-lfg
    - name: make gitag_mod_solo_lfg
      run: echo GITAG_MOD_SOLO_LFG=lfg$(git log --pretty=format:"%h" -1) >> $GITHUB_ENV
      working-directory: modules/mod-solo-lfg
    #mod-eluna
    - name: get mod-eluna
      uses: actions/checkout@v4
      with:
        repository: azerothcore/mod-eluna
        fetch-depth: 0
        path: modules/mod-eluna
    - run: git checkout $eluna_sha
      if: ${{ env.eluna_sha != '' }}
      working-directory: modules/mod-eluna
    - name: make gitag_mod_eluna
      run: echo GITAG_MOD_ELUNA=lua$(git log --pretty=format:"%h" -1) >> $GITHUB_ENV
      working-directory: modules/mod-eluna
    #mod-1v1-arena
    - name: get mod-1v1-arena
      uses: actions/checkout@v4
      with:
        repository: azerothcore/mod-1v1-arena
        fetch-depth: 0
        path: modules/mod-1v1-arena
    - run: git checkout $arena_sha
      if: ${{ env.arena_sha != '' }}
      working-directory: modules/mod-1v1-arena
    - name: make gitag_mod_1v1_arena
      run: echo GITAG_MOD_1V1_ARENA=1v1$(git log --pretty=format:"%h" -1) >> $GITHUB_ENV
      working-directory: modules/mod-1v1-arena
    #show tags
    - name: make docker image tag
      run: echo IMGTAG=$GITAG-$GITAG_MOD_PLAYERBOTS-$GITAG_MOD_AH_BOT-$GITAG_MOD_SOLO_LFG-$GITAG_MOD_1V1_ARENA-$GITAG_MOD_ELUNA >> $GITHUB_ENV
    - name: show docker tag
      run: echo $IMGTAG
    #build images
    - name: docker build 
      run: ./acore.sh docker build
    - name: build ac-tools
      run: docker compose build ac-tools
    - name: docker images
      run: docker images
    #push to aliyun registry
    - name: Docker Login
      uses: docker/login-action@v3.2.0
      with:
        registry: registry.us-west-1.aliyuncs.com
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PSW  }}
    - name: docker push ac-wotlk-authserver
      run: docker tag acore/ac-wotlk-authserver:master registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-authserver:$IMGTAG && docker  push registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-authserver:$IMGTAG
    - name: docker push ac-wotlk-worldserver
      run: docker tag acore/ac-wotlk-worldserver:master registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-worldserver:$IMGTAG &&  docker  push  registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-worldserver:$IMGTAG
    - name: docker push ac-wotlk-db-import
      run: docker tag acore/ac-wotlk-db-import:master registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-db-import:$IMGTAG &&   docker  push registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-db-import:$IMGTAG
    - name: docker push ac-wotlk-client-data
      run: docker tag acore/ac-wotlk-client-data:master registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-client-data:$IMGTAG &&   docker  push registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-client-data:$IMGTAG
    - name: docker push ac-wotlk-tools
      run: docker tag acore/ac-wotlk-tools:master registry.us-west-1.aliyuncs.com/out-of-wall/ac-tools:$IMGTAG &&   docker  push registry.us-west-1.aliyuncs.com/out-of-wall/ac-tools:$IMGTAG
    - name: docker push ac-wotlk-authserver
      run: docker tag acore/ac-wotlk-authserver:master registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-authserver:latest && docker  push registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-authserver:latest
    - name: docker push ac-wotlk-worldserver
      run: docker tag acore/ac-wotlk-worldserver:master registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-worldserver:latest &&  docker  push  registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-worldserver:latest
    - name: docker push ac-wotlk-db-import
      run: docker tag acore/ac-wotlk-db-import:master registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-db-import:latest &&   docker  push registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-db-import:latest
    - name: docker push ac-wotlk-client-data
      run: docker tag acore/ac-wotlk-client-data:master registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-client-data:latest &&   docker  push registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-client-data:latest
    - name: docker push ac-wotlk-tools
      run: docker tag acore/ac-wotlk-tools:master registry.us-west-1.aliyuncs.com/out-of-wall/ac-tools:latest &&   docker  push registry.us-west-1.aliyuncs.com/out-of-wall/ac-tools:latest
          
    
          
