name: Docker Image CI

on:
  push:
    branches: [ "Playerbot" ]
  pull_request:
    branches: [ "Playerbot" ]

env:
  master_sha: '7a47b27'
  playerbots_sha: '02786e6'
  ah_bot_sha: 'f3d285e'
  solo_lfg_sha: '97bf902'
  arena_sha: 'd8fc2b6'
  eluna_sha: 'c652ee8'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: git checkout $master_sha
      if: ${{ env.master_sha != '' }}
    - name: pwd && ls -l 
      run: pwd && ls -l 
    #gitag
    - name: make gitag
      run: echo GITAG=$(git log --pretty=format:"%h" -1) >> $GITHUB_ENV
      working-directory: ./
    #mod-playerbots
    - name: get mod-playerbots
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: liyunfan1223/mod-playerbots
        path: modules/mod-playerbots
    - run: git checkout $playerbots_sha
      if: ${{ env.playerbots_sha != '' }}
      working-directory: modules/mod-playerbots
    - name: make gitag_mod_playerbots
      run: echo GITAG_MOD_PLAYERBOTS=bot$(git log --pretty=format:"%h" -1) >> $GITHUB_ENV
      working-directory: modules/mod-playerbots
    #mod-ah-bot
    - name: get mod-ah-bot
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: azerothcore/mod-ah-bot
        path: modules/mod-ah-bot
    - run: git checkout $ah_bot_sha
      if: ${{ env.ah_bot_sha != '' }}
      working-directory: modules/mod-ah-bot
    - name: make gitag_mod_ah_bot
      run: echo GITAG_MOD_AH_BOT=ah$(git log --pretty=format:"%h" -1) >> $GITHUB_ENV
      working-directory: modules/mod-ah-bot
    #mod-solo-lfg
    - name: get mod-solo-lfg
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: azerothcore/mod-solo-lfg
        path: modules/mod-solo-lfg
    - run: git checkout $solo_lfg_sha
      if: ${{ env.solo_lfg_sha != '' }}
      working-directory: modules/mod-solo-lfg
    - name: make gitag_mod_solo_lfg
      run: echo GITAG_MOD_SOLO_LFG=lfg$(git log --pretty=format:"%h" -1) >> $GITHUB_ENV
      working-directory: modules/mod-solo-lfg
    #mod-1v1-arena
    - name: get mod-1v1-arena
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: azerothcore/mod-1v1-arena
        path: modules/mod-1v1-arena
    - run: git checkout $arena_sha
      if: ${{ env.arena_sha != '' }}
      working-directory: modules/mod-1v1-arena
    - name: make gitag_mod_1v1_arena
      run: echo GITAG_MOD_1V1_ARENA=1v1$(git log --pretty=format:"%h" -1) >> $GITHUB_ENV
      working-directory: modules/mod-1v1-arena
    #mod-eluna
    - name: get mod-eluna
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        repository: azerothcore/mod-eluna
        path: modules/mod-eluna
    - run: sleep 1s && git checkout $eluna_sha
      if: ${{ env.eluna_sha != '' }}
      working-directory: modules/mod-eluna
    - name: make gitag_mod_eluna
      run: echo GITAG_MOD_ELUNA=lua$(git log --pretty=format:"%h" -1) >> $GITHUB_ENV
      working-directory: modules/mod-eluna
    #show tags
    - name: make docker image tag
      run: echo IMGTAG=$GITAG-$GITAG_MOD_PLAYERBOTS-$GITAG_MOD_AH_BOT-$GITAG_MOD_SOLO_LFG-$GITAG_MOD_1V1_ARENA-$GITAG_MOD_ELUNA >> $GITHUB_ENV
    - name: show docker tag
      run: echo $IMGTAG
    
          
