name: Docker Image CI

on:
  push:
    branches: [ "Playerbot" ]
  pull_request:
    branches: [ "Playerbot" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: pwd && ls -l 
      run: pwd && ls -l 
    - name: get mod-playerbots
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        # Repository owner and name. Ex: sudosubin/git-clone-action
        repository: liyunfan1223/mod-playerbots
        # Git host platform. Ex: github, gitlab, bitbucket, gitee, or else (git.suckless.org, ...)
        # platform: # optional, default is github
        # Git branch or tag to checkout.
        ref: master
        # Relative path from current directory, where to clone.
        path: modules/mod-playerbots
    - name: get mod-ah-bot
      uses: sudosubin/git-clone-action@v1.0.1
      with:
        # Repository owner and name. Ex: sudosubin/git-clone-action
        repository: azerothcore/mod-ah-bot
        # Git host platform. Ex: github, gitlab, bitbucket, gitee, or else (git.suckless.org, ...)
        # platform: # optional, default is github
        # Git branch or tag to checkout.
        # ref: master
        # Relative path from current directory, where to clone.
        path: modules/mod-ah-bot
    - name: docker build 
      run: ./acore.sh docker build
    - name: build ac-tools
      run: docker compose build ac-tools
    - name: docker images
      run: docker images
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
      uses: docker/login-action@v3.2.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: registry.us-west-1.aliyuncs.com
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PSW  }}
        # Specifies whether the given registry is ECR (auto, true or false)
        #ecr: # optional, default is auto
        # Log out from the Docker registry at the end of a job
        #logout: # optional, default is true
    - name: docker push ac-wotlk-authserver
      run: docker tag acore/ac-wotlk-authserver:master registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-authserver:$(git log --pretty=format:"%h" -1) && docker  push registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-authserver:$(git log --pretty=format:"%h" -1)
    - name: docker push ac-wotlk-worldserver
      run: docker tag acore/ac-wotlk-worldserver:master registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-worldserver:$(git log --pretty=format:"%h" -1) &&  docker  pull  registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-worldserver:$(git log --pretty=format:"%h" -1)
    - name: docker push ac-wotlk-db-import
      run: docker tag acore/ac-wotlk-db-import:master registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-db-import:$(git log --pretty=format:"%h" -1) &&   docker  pull registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-db-import:$(git log --pretty=format:"%h" -1)
    - name: docker push ac-wotlk-client-data
      run: docker tag acore/ac-wotlk-client-data:master registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-client-data:$(git log --pretty=format:"%h" -1) &&   docker  pull registry.us-west-1.aliyuncs.com/out-of-wall/ac-wotlk-client-data:$(git log --pretty=format:"%h" -1)
    - name: docker push ac-tools
      run: docker tag acore/ac-tools:master registry.us-west-1.aliyuncs.com/out-of-wall/ac-tools:$(git log --pretty=format:"%h" -1) &&   docker  pull registry.us-west-1.aliyuncs.com/out-of-wall/ac-tools:$(git log --pretty=format:"%h" -1)
          
